require("yashwanth.plugins-setup")
require("yashwanth.core.options")
require("yashwanth.core.keymaps")
require("yashwanth.core.colorscheme")
require("yashwanth.plugins.comment")
require("yashwanth.plugins.nvim-tree")
require("yashwanth.plugins.lualine")
require("yashwanth.plugins.telescope")
require("yashwanth.plugins.nvim-cmp")
require("yashwanth.plugins.lsp.mason")
require("yashwanth.plugins.lsp.lspsaga")
require("yashwanth.plugins.lsp.lspconfig")
require("yashwanth.plugins.lsp.null-ls")
require("yashwanth.plugins.autopairs")
require("yashwanth.plugins.lsp.treesitter")
require("yashwanth.plugins.lsp.gitsigns")

